### ISSUE TITLE
对简历的评论

### ISSUE THREAD

**Issue by jshancn** [whps/whps.github.io#29]
### 问题
- 求职意向一定要写在开头啊！！！
- 技术和项目经历写得有层次一些，让人一眼就能获得需要信息。比如开发周期和所用技术。
- 个人感想的东西集中在一起提一下就好，不必写太多占用信息展示的空间。

### 目标
简历的目标就是以最简略的话语尽可能全面的展示自己的技能和特长。所以要有层次，语言简略。关于一些细节的内容和个人感想可以在面试的时候详谈。

**Comment by whps** [comment]
感谢 @jshancn  的建议，很有用也很重要！！！
